name: 'Smoketest for Logitech Media Server'
on:
  push:
  workflow_dispatch:
  pull_request_target:
    types: [assigned, labeled]
jobs:
  linux:
    name: Run LMS to see whether it crashes immediately...
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: Run test
        run: bash t/00_smoketest.sh
